name: cowchain_farm_alert
description: A notification app for Cowchain Farm.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  http: ^1.1.0
  fixnum: ^1.1.0
  provider: ^6.0.5
  stellar_flutter_sdk:
    git:
      # when using CodeMagic, always use HTTPS for github instead of GIT
      url: https://github.com/hasToDev/stellar_flutter_sdk.git
      ref: f447a6ade7db4f7c13ecd01fb5a129800d5dcec3

#dependency_overrides:
#  stellar_flutter_sdk:
#    path: ../stellar_flutter_sdk

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
